num  = int(input('Insira o valor da tabuada: '))
print(f'{num} x {1:2} = {num*1}')
print(f'{num} x {2:2} = {num*2}')
print(f'{num} x {3:2} = {num*3}')
print(f'{num} x {4:2} = {num*4}')
print(f'{num} x {5:2} = {num*5}')
print(f'{num} x {6:2} = {num*6}')
print(f'{num} x {7:2} = {num*7}')
print(f'{num} x {8:2} = {num*8}')
print(f'{num} x {9:2} = {num*9}')
print(f'{num} x {10:2} = {num*10}')

# valor = int(input('Insira o valor da tabuada: ')
# print(f'1x1 = {1 * valor }')
# print(f'1x2 = {2 * valor }')
# print(f'1x3 = {3 * valor }')
# print(f'1x4 = {4 * valor }')
# print(f'1x5 = {5 * valor }')
# print(f'1x6 = {6 * valor }')
# print(f'1x7 = {7 * valor }')
# print(f'1x8 = {8 * valor }')
# print(f'1x9 = {9 * valor }')
# print(f'1x10 = {10 * valor }')


